name: FTP upload
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # master ブランチの取得
      - name: Checkout
        uses: actions/checkout@v3
      # Node.jsのセットアップ
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      # パッケージのインストール
      - name: Install dependencies
        run: yarn --frozen-lockfile
      # テスト
      #
      # ビルド
      - name: Build
        run: yarn build

  deploy:
      needs: [build]
      # さくらレンタルサーバにデプロイ
      - name: Sakura FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./out/
          server-dir: /home/halrs/www/
